name = "lean-signal-api"
main = "src/worker.js"
compatibility_date = "2023-08-23"

[unsafe.metadata.observability]
enabled = true

[[kv_namespaces]]
binding = "SIGNALS"
id = "d91ec6cd4cfb4130a5aaae0a289d5c7d"