/*
name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Authenticate Wrangler
        run: echo "api_token=${{ secrets.CF_API_TOKEN }}" > ~/.wrangler/config/default.toml

      - name: Publish to Workers
        run: wrangler publish
*/
